
name: Build with Visual Studio 2022

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild from Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BepInExInstall.sln

    - name: Build with Visual Studio 2022 MSBuild
      run: msbuild BepInExInstall.sln /p:Configuration=Release

    - name: Show build output
      run: dir bin\Release\

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BepInExInstall
        path: bin/Release/
