
name: Build BepInExInstall (VS2022)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild (Visual Studio 2022)
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BepInExInstall.sln

    - name: Build project
      run: msbuild BepInExInstall.sln /p:Configuration=Release

    - name: Show build output
      run: dir bin\Release\

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: BepInExInstall
        path: bin/Release/
