
name: Build and Release BepInExInstall

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild (Visual Studio 2022)
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BepInExInstall.sln

    - name: Build with MSBuild
      run: msbuild BepInExInstall.sln /p:Configuration=Release

    - name: Install ILMerge
      run: choco install ilmerge -y

    - name: Merge EXE with ILMerge (global install)
      shell: cmd
      run: |
        echo Running ILMerge...
        ILMerge.exe ^
          /target:winexe ^
          /targetplatform:v4,C:\Windows\Microsoft.NET\Framework4.0.30319 ^
          /out:bin\Release\BepInExInstall.exe ^
          bin\Release\BepInExInstall.exe ^
          bin\Release\MetroFramework.dll ^
          bin\Release\MetroFramework.Fonts.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: BepInExInstall
        path: bin/Release/

    - name: Package for Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir release
        copy bin\Release\*.exe release        powershell Compress-Archive -Path release\* -DestinationPath BepInExInstall.zip

    - name: Generate release notes
      run: |
        echo "# 🚀 BepInExInstall Release" > RELEASE.md
        echo "" >> RELEASE.md
        echo "Easily install and manage BepInEx & UnityExplorer for Unity games." >> RELEASE.md
        echo "" >> RELEASE.md
        echo "## 📦 Features" >> RELEASE.md
        echo "- One-click BepInEx install (v5/v6 supported)" >> RELEASE.md
        echo "- UnityExplorer integration" >> RELEASE.md
        echo "- Drag & Drop game .exe" >> RELEASE.md
        echo "- Automatic Unity version & architecture detection" >> RELEASE.md
        echo "- Config editor (BepInEx.cfg)" >> RELEASE.md

    - name: Publish GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BepInExInstall.zip
          bin/Release/BepInExInstall.exe
        body_path: RELEASE.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
