
name: Build and Release with Visual Studio 2022

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild from Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BepInExInstall.sln

    - name: Build project
      run: msbuild BepInExInstall.sln /p:Configuration=Release

    - name: Zip release output
      run: |
        mkdir release
        copy bin\Release\*.exe release\
        powershell Compress-Archive -Path release\* -DestinationPath BepInExInstall.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: BepInExInstall.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
