
name: Build and Release BepInExInstall

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild (Visual Studio 2022)
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BepInExInstall.sln

    - name: Build with MSBuild
      run: msbuild BepInExInstall.sln /p:Configuration=Release

    - name: Merge EXE with ILMerge (overwrite original)
      shell: cmd
      run: |
        echo Running ILMerge...
        packages\ILMerge.Tools.2.14.1203	ools
et452\ILMerge.exe ^
          /target:winexe ^
          /targetplatform:v4,C:\Windows\Microsoft.NET\Framework4.0.30319 ^
          /out:bin\Release\BepInExInstall.exe ^
          bin\Release\BepInExInstall.exe ^
          bin\Release\MetroFramework.dll ^
          bin\Release\MetroFramework.Fonts.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: BepInExInstall
        path: bin/Release/

    - name: Generate release notes
      run: |
        echo "# 🚀 BepInExInstall Release" > RELEASE.md
        echo "" >> RELEASE.md
        echo "Standalone executable with BepInEx + MetroFramework support." >> RELEASE.md
        echo "" >> RELEASE.md
        echo "Includes:" >> RELEASE.md
        echo "- Single-file .exe (no DLLs required)" >> RELEASE.md
        echo "- Built from latest commit" >> RELEASE.md

    - name: Package for Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir release
        copy bin\Release\BepInExInstall.exe release\
        powershell Compress-Archive -Path release\* -DestinationPath BepInExInstall.zip

    - name: Publish GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BepInExInstall.zip
          bin/Release/BepInExInstall.exe
        body_path: RELEASE.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
